export interface LabourInquiryField {
  id: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'multiselect' | 'date' | 'textarea' | 'toggle';
  options?: string[];
  required: boolean;
  placeholder?: string;
}

export interface LabourInquirySchema {
  id: string;
  fields: LabourInquiryField[];
}

const baseFields: LabourInquiryField[] = [
  { id: 'number_of_workers', label: 'Number of Workers', type: 'number', required: true },
  { id: 'start_date', label: 'Start Date', type: 'date', required: true },
  { id: 'duration', label: 'Duration', type: 'select', options: ['Daily', 'Weekly', 'Monthly', 'Project-Based'], required: true },
  { id: 'location', label: 'Location', type: 'text', required: true },
  { id: 'rate_preference', label: 'Rate Preference', type: 'select', options: ['Hourly', 'Daily', 'Weekly', 'Monthly'], required: true },
  { id: 'additional_notes', label: 'Additional Notes', type: 'textarea', required: false },
];

export const labourInquirySchemas: Record<string, LabourInquirySchema> = {
  genericLabourInquirySchema: { id: 'genericLabourInquirySchema', fields: [...baseFields] },

  // CONSTRUCTION
  generalLabourerInquirySchema: { id: 'generalLabourerInquirySchema', fields: [...baseFields, { id: 'site_type', label: 'Site Type', type: 'select', options: ['Residential', 'Commercial', 'Industrial', 'Road'], required: true }, { id: 'tools_provided', label: 'Tools Provided', type: 'toggle', required: true }, { id: 'physical_requirements', label: 'Physical Requirements', type: 'select', options: ['Light', 'Medium', 'Heavy'], required: true }] },
  bricklayerInquirySchema: { id: 'bricklayerInquirySchema', fields: [...baseFields, { id: 'work_type', label: 'Work Type', type: 'select', options: ['New Build', 'Repair', 'Renovation'], required: true }, { id: 'has_own_tools', label: 'Must Have Own Tools', type: 'toggle', required: true }, { id: 'brick_type', label: 'Brick Type', type: 'select', options: ['Concrete Blocks', 'Face Bricks', 'Compressed Earth', 'Other'], required: true }] },
  carpenterInquirySchema: { id: 'carpenterInquirySchema', fields: [...baseFields, { id: 'carpentry_type', label: 'Carpentry Type', type: 'select', options: ['Structural', 'Finish', 'General', 'Furniture'], required: true }, { id: 'wood_preference', label: 'Wood Preference', type: 'text', required: false, placeholder: 'e.g. Pine, Oak, Rosewood' }, { id: 'is_custom_build', label: 'Is Global Custom Build', type: 'toggle', required: false }] },
  electricianInquirySchema: { id: 'electricianInquirySchema', fields: [...baseFields, { id: 'work_type', label: 'Work Type', type: 'select', options: ['New Installation', 'Repair', 'Inspection', 'Rewiring'], required: true }, { id: 'property_type', label: 'Property Type', type: 'select', options: ['Residential', 'Commercial', 'Industrial'], required: true }, { id: 'certifications_required', label: 'Certifications Required', type: 'toggle', required: true }, { id: 'materials_provided', label: 'Materials Provided', type: 'toggle', required: true }] },
  plumberInquirySchema: { id: 'plumberInquirySchema', fields: [...baseFields, { id: 'work_type', label: 'Work Type', type: 'select', options: ['Installation', 'Repair', 'Maintenance'], required: true }, { id: 'is_emergency', label: 'Is Emergency?', type: 'toggle', required: true }, { id: 'pipe_material', label: 'Pipe Material', type: 'select', options: ['PVC', 'Copper', 'Galvanized', 'PEX'], required: false }] },
  welderInquirySchema: { id: 'welderInquirySchema', fields: [...baseFields, { id: 'welding_type', label: 'Welding Type', type: 'select', options: ['MIG', 'TIG', 'Arc', 'Gas'], required: true }, { id: 'material_to_weld', label: 'Material to Weld', type: 'select', options: ['Mild Steel', 'Stainless Steel', 'Aluminum', 'Cast Iron'], required: true }, { id: 'power_source_on_site', label: 'Power Source on Site', type: 'toggle', required: true }] },
  steelFixerInquirySchema: { id: 'steelFixerInquirySchema', fields: [...baseFields, { id: 'project_type', label: 'Project Type', type: 'select', options: ['Commercial', 'Residential', 'Infrastructure'], required: true }, { id: 'bar_size_range', label: 'Max Bar Size (mm)', type: 'number', required: false }, { id: 'drawings_available', label: 'Techncial Drawings Available', type: 'toggle', required: true }] },
  painterInquirySchema: { id: 'painterInquirySchema', fields: [...baseFields, { id: 'surface_type', label: 'Surface Type', type: 'select', options: ['Interior', 'Exterior', 'Both'], required: true }, { id: 'paint_provided', label: 'Paint Provided by Buyer', type: 'toggle', required: true }, { id: 'area_size_description', label: 'Area Description', type: 'text', required: false, placeholder: 'e.g. 3 Bedrooms, Perimeter wall' }] },
  tilerInquirySchema: { id: 'tilerInquirySchema', fields: [...baseFields, { id: 'tile_type', label: 'Tile Type', type: 'select', options: ['Ceramic', 'Porcelain', 'Natural Stone', 'Vinyl'], required: true }, { id: 'area_sqm', label: 'Approx Area (sqm)', type: 'number', required: true }, { id: 'adhesive_provided', label: 'Adhesive Provided', type: 'toggle', required: true }] },
  rooferInquirySchema: { id: 'rooferInquirySchema', fields: [...baseFields, { id: 'roof_type', label: 'Roof Type', type: 'select', options: ['Flat', 'Pitched', 'MetalSheets', 'Concrete Tiles', 'Thatch'], required: true }, { id: 'leakage_repair', label: 'Is Leakage Repair?', type: 'toggle', required: true }, { id: 'height_from_ground', label: 'Building Height (Floors)', type: 'number', required: false }] },

  // DOMESTIC
  houseCleanerInquirySchema: { id: 'houseCleanerInquirySchema', fields: [...baseFields, { id: 'cleaning_type', label: 'Cleaning Type', type: 'select', options: ['Standard', 'Deep', 'Move-in/out', 'Post-Construction'], required: true }, { id: 'frequency', label: 'Frequency', type: 'select', options: ['Once-off', 'Weekly', 'Daily', 'Monthly'], required: true }, { id: 'cleaning_supplies_provided', label: 'Supplies Provided', type: 'toggle', required: true }] },
  nannyInquirySchema: { id: 'nannyInquirySchema', fields: [...baseFields, { id: 'number_of_children', label: 'Number of Children', type: 'number', required: true }, { id: 'live_in_out', label: 'Arrangement', type: 'select', options: ['Live-in', 'Live-out'], required: true }, { id: 'childcare_experience_years', label: 'Min Experience Years', type: 'number', required: false }] },
  cookInquirySchema: { id: 'cookInquirySchema', fields: [...baseFields, { id: 'cuisine_type', label: 'Cuisine Style', type: 'text', required: true, placeholder: 'e.g. Zambian, Continental, Indian' }, { id: 'service_frequency', label: 'Frequency', type: 'select', options: ['Full-time', 'Part-time', 'Event Only'], required: true }, { id: 'ingredients_sourced_by', label: 'Buyer Sources Ingredients', type: 'toggle', required: true }] },
  gardenerInquirySchema: { id: 'gardenerInquirySchema', fields: [...baseFields, { id: 'garden_size', label: 'Garden Size', type: 'select', options: ['Small', 'Medium', 'Large', 'Estate'], required: true }, { id: 'mowing_required', label: 'Mowing Required', type: 'toggle', required: true }, { id: 'tools_provided', label: 'Tools Provided', type: 'toggle', required: true }] },
  houseHelpInquirySchema: { id: 'houseHelpInquirySchema', fields: [...baseFields, { id: 'duties', label: 'Duties', type: 'multiselect', options: ['Cleaning', 'Cooking', 'Laundry', 'Childcare'], required: true }] },
  laundryInquirySchema: { id: 'laundryInquirySchema', fields: [...baseFields, { id: 'service_type', label: 'Service Type', type: 'select', options: ['Wash & Fold', 'Ironing Only', 'Wash & Iron', 'Dry Cleaning'], required: true }, { id: 'pickup_delivery', label: 'Pickup/Delivery Needed', type: 'toggle', required: true }, { id: 'bulk_laundry', label: 'Is Bulk Order?', type: 'toggle', required: false }] },

  // INDUSTRIAL
  machineOperatorInquirySchema: { id: 'machineOperatorInquirySchema', fields: [...baseFields, { id: 'machine_type', label: 'Machine/Equipment Type', type: 'text', required: true }, { id: 'industry_vertical', label: 'Industry', type: 'select', options: ['Mining', 'Manufacturing', 'Agriculture', 'Construction'], required: true }, { id: 'license_required', label: 'Operating License Required', type: 'toggle', required: true }] },
  warehouseWorkerInquirySchema: { id: 'warehouseWorkerInquirySchema', fields: [...baseFields, { id: 'shift_type', label: 'Shift Type', type: 'select', options: ['Day', 'Night', 'Rotating'], required: true }, { id: 'needs_forklift_license', label: 'Needs Forklift Skills', type: 'toggle', required: true }, { id: 'heavy_lifting_required', label: 'Heavy Lifting (25kg+)', type: 'toggle', required: true }] },
  factoryHandInquirySchema: { id: 'factoryHandInquirySchema', fields: [...baseFields, { id: 'factory_type', label: 'Factory Type', type: 'text', required: true }, { id: 'repetitive_tasks', label: 'Repetitive Physical Tasks', type: 'toggle', required: true }, { id: 'protective_gear_provided', label: 'PPE Provided', type: 'toggle', required: true }] },
  forkliftOperatorInquirySchema: { id: 'forkliftOperatorInquirySchema', fields: [...baseFields, { id: 'license_type', label: 'License Code', type: 'text', required: true, placeholder: 'e.g. Code 11' }, { id: 'environment_type', label: 'Work Environment', type: 'select', options: ['Indoor Warehouse', 'Outdoor Yard', 'Refrigerated/Cold'], required: true }, { id: 'max_lift_weight', label: 'Max Lift Target (Tons)', type: 'number', required: false }] },
  safetyOfficerInquirySchema: { id: 'safetyOfficerInquirySchema', fields: [...baseFields, { id: 'industry', label: 'Industry Focus', type: 'select', options: ['Construction', 'Mining', 'Health & Safety', 'Corporate'], required: true }, { id: 'certifications_min', label: 'Required Certs', type: 'text', required: false, placeholder: 'e.g. NEBOSH, IOSH' }, { id: 'full_time_site_presence', label: 'Full Site Presence', type: 'toggle', required: true }] },

  // SKILLED TRADES
  hvacTechnicianInquirySchema: { id: 'hvacTechnicianInquirySchema', fields: [...baseFields, { id: 'hvac_type', label: 'Service Need', type: 'select', options: ['Installation', 'Repair', 'Maintenance', 'Gas Refill'], required: true }, { id: 'unit_type', label: 'Unit Type', type: 'select', options: ['Split Unit', 'Central System', 'Industrial Chillers', 'Portable'], required: true }, { id: 'number_of_units', label: 'Unit Count', type: 'number', required: false }] },
  autoMechanicInquirySchema: { id: 'autoMechanicInquirySchema', fields: [...baseFields, { id: 'vehicle_type', label: 'Vehicle Category', type: 'select', options: ['Sedan/Hatch', 'SUV/4x4', 'Truck', 'Motorcycle'], required: true }, { id: 'repair_focus', label: 'Focus Area', type: 'select', options: ['Engine', 'Suspension', 'Brakes', 'Electrical', 'General Service'], required: true }, { id: 'parts_on_site', label: 'Parts Already Purchased', type: 'toggle', required: true }] },
  sprayPainterInquirySchema: { id: 'sprayPainterInquirySchema', fields: [...baseFields, { id: 'surface_type', label: 'Surface Material', type: 'select', options: ['Automotive', 'Metal Structures', 'Wood Products'], required: true }, { id: 'is_paint_booth_available', label: 'Paint Booth Available', type: 'toggle', required: true }, { id: 'paint_finish_type', label: 'Finish Type', type: 'select', options: ['Matte', 'Gloss', 'Metallic', 'Undercoat Only'], required: true }] },
  glazierInquirySchema: { id: 'glazierInquirySchema', fields: [...baseFields, { id: 'glass_type', label: 'Glass Requirement', type: 'select', options: ['Clear Float', 'Toughened', 'Laminated', 'Tinted', 'Mirror'], required: true }, { id: 'is_high_rise', label: 'Above Ground Floor?', type: 'toggle', required: true }, { id: 'frame_material', label: 'Frame Material', type: 'select', options: ['Aluminum', 'Wood', 'Steel', 'Frameless'], required: false }] },
  securityGuardInquirySchema: { id: 'securityGuardInquirySchema', fields: [...baseFields, { id: 'shift_type', label: 'Shift Requirement', type: 'select', options: ['Day Only', 'Night Only', 'Day/Night Relief', '24/7 Deployment'], required: true }, { id: 'guard_type', label: 'Guard Level', type: 'select', options: ['Standard', 'Corporate/VIP', 'Armed (Request Review)', 'K9 Handler'], required: true }, { id: 'uniform_provided_by_client', label: 'Uniform Provided by Client', type: 'toggle', required: true }] },

  // AGRICULTURAL
  farmWorkerInquirySchema: { id: 'farmWorkerInquirySchema', fields: [...baseFields, { id: 'task_type', label: 'Primary Task', type: 'select', options: ['Land Preparation', 'Planting', 'Weeding', 'Manual Irrigation', 'General Maintenance'], required: true }, { id: 'seasonal_engagement', label: 'Is Seasonal Period?', type: 'toggle', required: true }, { id: 'accommodation_available', label: 'Housing on Farm', type: 'toggle', required: true }] },
  irrigationTechnicianInquirySchema: { id: 'irrigationTechnicianInquirySchema', fields: [...baseFields, { id: 'system_type', label: 'System Type', type: 'select', options: ['Drip', 'Center Pivot', 'Sprinkler', 'Solar Pump System'], required: true }, { id: 'pump_repair_needed', label: 'Pump Repair Needed', type: 'toggle', required: true }, { id: 'acreage_size', label: 'Land Size (Hectares)', type: 'number', required: false }] },
  cropHarvestingInquirySchema: { id: 'cropHarvestingInquirySchema', fields: [...baseFields, { id: 'crop_type', label: 'Crop Category', type: 'select', options: ['Grain/Maize', 'Vegetables', 'Fruits', 'Tobacco/Commercial'], required: true }, { id: 'harvesting_method', label: 'Method', type: 'select', options: ['Manual Only', 'Machine Assisted', 'Both'], required: true }, { id: 'storage_on_site', label: 'Internal Storage Available', type: 'toggle', required: true }] },
  livestockHandlerInquirySchema: { id: 'livestockHandlerInquirySchema', fields: [...baseFields, { id: 'livestock_type', label: 'Animal Type', type: 'select', options: ['Poultry', 'Cattle', 'Pigs', 'Goats/Sheep', 'Fish Farming'], required: true }, { id: 'veterinary_knowledge_req', label: 'Basic Vet Knowledge Required', type: 'toggle', required: true }, { id: 'shift_rotation', label: 'Night Watch Included', type: 'toggle', required: true }] },
  equipmentOperatorAgriInquirySchema: { id: 'equipmentOperatorAgriInquirySchema', fields: [...baseFields, { id: 'equipment_type', label: 'Primary Machine', type: 'select', options: ['Tractor', 'Combine Harvester', 'Planter', 'Boom Sprayer'], required: true }, { id: 'valid_tractor_license', label: 'Valid License Required', type: 'toggle', required: true }, { id: 'mechanical_basics', label: 'Basic Maintenance Skills Required', type: 'toggle', required: true }] },

  // TRANSPORT
  driverLightInquirySchema: { id: 'driverLightInquirySchema', fields: [...baseFields, { id: 'vehicle_provided', label: 'Vehicle Provided', type: 'toggle', required: true }, { id: 'license_class_required', label: 'License Class Required', type: 'select', options: ['B', 'C', 'C1'], required: true }, { id: 'trip_type', label: 'Trip Type', type: 'select', options: ['One-Way', 'Return', 'Full Day', 'Part Day'], required: true }, { id: 'load_type', label: 'Load Type', type: 'select', options: ['Passengers', 'Goods', 'Mixed'], required: true }] },
  driverHeavyInquirySchema: { id: 'driverHeavyInquirySchema', fields: [...baseFields, { id: 'vehicle_type_heavy', label: 'Truck Type', type: 'select', options: ['Rigid Truck', 'Articulated / Horse', 'Tipper', 'Tanker', 'Bus / coach'], required: true }, { id: 'interstate_border_cross', label: 'Cross-Border Travel Required', type: 'toggle', required: true }, { id: 'hazmat_valid', label: 'Dangerous Goods Permitted', type: 'toggle', required: true }] },
  loaderInquirySchema: { id: 'loaderInquirySchema', fields: [...baseFields, { id: 'load_type', label: 'Goods Category', type: 'select', options: ['Household/Furniture', 'Construction Materials', 'Warehouse Cargo', 'Industrial/Heavy'], required: true }, { id: 'fragile_items', label: 'Contains Fragile Items', type: 'toggle', required: true }, { id: 'number_of_loaders_total', label: 'Team Size Requested', type: 'number', required: false }] },
  deliveryRiderInquirySchema: { id: 'deliveryRiderInquirySchema', fields: [...baseFields, { id: 'delivery_type', label: 'Delivery Items', type: 'select', options: ['Food/Documents', 'Retail/E-commerce', 'Medical Supplies', 'General Small Loads'], required: true }, { id: 'bike_provided_by_client', label: 'Motorcycle Provided', type: 'toggle', required: true }, { id: 'smartphone_required', label: 'Must Have Own Smartphone', type: 'toggle', required: true }] },
};
