import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784125563968 implements MigrationInterface {
    name = 'InitialSchema1784125563968'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."identity_audits_eventtype_enum" AS ENUM('USER_REGISTERED', 'NRC_VERIFIED', 'NRC_VERIFICATION_FAILED', 'EMAIL_ADDED', 'EMAIL_REMOVED', 'EMAIL_PRIMARY_CHANGED', 'EMAIL_VERIFIED', 'PASSWORD_CHANGED', 'ACCOUNT_SUSPENDED', 'ACCOUNT_REACTIVATED', 'ACCOUNT_DELETED', 'SUSPICIOUS_ACTIVITY', 'ADMIN_ACTION')`);
        await queryRunner.query(`CREATE TYPE "public"."identity_audits_verificationstatus_enum" AS ENUM('UNVERIFIED', 'VERIFIED', 'FRAUD')`);
        await queryRunner.query(`CREATE TABLE "identity_audits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "eventType" "public"."identity_audits_eventtype_enum" NOT NULL, "description" text NOT NULL, "previousValue" jsonb, "newValue" jsonb, "changedField" character varying(100), "adminId" uuid, "ipAddress" character varying(50), "userAgent" text, "isSuspicious" boolean NOT NULL DEFAULT false, "metadata" jsonb, "verificationStatus" "public"."identity_audits_verificationstatus_enum" NOT NULL DEFAULT 'UNVERIFIED', "statusNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_233daa71279feaef45f09130c30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_identity_audits_user_date" ON "identity_audits" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_identity_audits_user_event" ON "identity_audits" ("userId", "eventType") `);
        await queryRunner.query(`CREATE INDEX "idx_identity_audits_created_at" ON "identity_audits" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_identity_audits_event_type" ON "identity_audits" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "idx_identity_audits_user_id" ON "identity_audits" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('BUYER', 'SELLER', 'SERVICE_PROVIDER', 'ADMIN', 'PROMOTER')`);
        await queryRunner.query(`CREATE TYPE "public"."users_activeprofiletype_enum" AS ENUM('BUYER', 'SELLER', 'SERVICE_PROVIDER')`);
        await queryRunner.query(`CREATE TYPE "public"."users_departmentautonomy_enum" AS ENUM('INDEPENDENT', 'MANAGED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nrcNumber" character varying(50), "displayId" character varying(20), "password" text NOT NULL, "refreshToken" character varying(500), "passwordResetTokenHash" character varying(64), "passwordResetTokenExpiresAt" TIMESTAMP, "role" "public"."users_role_enum" NOT NULL DEFAULT 'BUYER', "name" character varying(255), "isNrcVerified" boolean NOT NULL DEFAULT false, "nrcDocumentPath" text, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, "lastNrcVerificationAt" TIMESTAMP, "activeProfileId" uuid, "activeProfileType" "public"."users_activeprofiletype_enum", "parentProviderId" uuid, "permissions" text, "assignedArchetype" character varying(32), "mustChangePassword" boolean NOT NULL DEFAULT false, "isDepartmentHead" boolean NOT NULL DEFAULT false, "departmentAutonomy" "public"."users_departmentautonomy_enum", "canMoveFinance" boolean NOT NULL DEFAULT false, "pin" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_402d48872fc4d6bd4e36dc3b78b" UNIQUE ("nrcNumber"), CONSTRAINT "UQ_fab8abf5c6f575391f6e6005322" UNIQUE ("displayId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_parent_provider" ON "users" ("parentProviderId") `);
        await queryRunner.query(`CREATE INDEX "idx_users_password_reset_token_hash" ON "users" ("passwordResetTokenHash") `);
        await queryRunner.query(`CREATE INDEX "idx_users_updated_at" ON "users" ("updatedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_users_created_at" ON "users" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_display_id" ON "users" ("displayId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_nrc" ON "users" ("nrcNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."user_emails_verificationstatus_enum" AS ENUM('NOT_VERIFIED', 'VERIFICATION_SENT', 'VERIFIED')`);
        await queryRunner.query(`CREATE TABLE "user_emails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "email" character varying(255) NOT NULL, "isPrimary" boolean NOT NULL DEFAULT false, "verificationStatus" "public"."user_emails_verificationstatus_enum" NOT NULL DEFAULT 'NOT_VERIFIED', "verificationToken" character varying(255), "verificationTokenExpiresAt" TIMESTAMP, "verifiedAt" TIMESTAMP, "isRecoveryEmail" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6594597afde633cfeab9a806e4f" UNIQUE ("email"), CONSTRAINT "PK_3ef6c4be97ba94ea3ba65362ad0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_emails_created_at" ON "user_emails" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_user_emails_verification_status" ON "user_emails" ("verificationStatus") `);
        await queryRunner.query(`CREATE INDEX "idx_user_emails_is_primary" ON "user_emails" ("isPrimary") `);
        await queryRunner.query(`CREATE INDEX "idx_user_emails_user_id" ON "user_emails" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_user_emails_email" ON "user_emails" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."service_provider_profiles_verificationstatus_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', 'INCOMPLETE')`);
        await queryRunner.query(`CREATE TABLE "service_provider_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying(255), "email" character varying(255), "phone" character varying(20), "dateOfBirth" date, "profilePicture" text, "logo" text, "coverImage" text, "socialLinks" text, "subRole" character varying(50), "labourCategory" character varying(50), "labourSubTypes" text NOT NULL DEFAULT '', "companyName" character varying(255), "tpin" character varying(20), "incorporationCertUrl" text, "businessLicenseId" uuid, "bozLicenceNumber" character varying(100), "bozLicenceUrl" text, "loanTerms" json, "verificationStatus" "public"."service_provider_profiles_verificationstatus_enum" NOT NULL DEFAULT 'PENDING', "verificationRejectionReason" text, "verifiedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "province" character varying(100), "city" character varying(100), "area" character varying(255), "latitude" numeric(10,7), "longitude" numeric(10,7), "radius" numeric(6,2), "pin" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7773baf7a80a7b9c32954def5ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_service_provider_profiles_verification" ON "service_provider_profiles" ("verificationStatus") `);
        await queryRunner.query(`CREATE INDEX "idx_service_provider_profiles_user" ON "service_provider_profiles" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."categories_archetype_enum" AS ENUM('RETAIL', 'RENTAL', 'BOOKING', 'LABOUR', 'REPAIR', 'SERVICE', 'EVENTS', 'ENTERTAINMENT', 'WHOLESALE', 'LENDING')`);
        await queryRunner.query(`CREATE TYPE "public"."categories_nature_enum" AS ENUM('PRODUCT', 'SERVICE', 'BOTH')`);
        await queryRunner.query(`CREATE TYPE "public"."categories_actionvariant_enum" AS ENUM('BUY_NEW', 'REPAIR')`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" character varying(64) NOT NULL, "name" character varying(255) NOT NULL, "parentId" character varying(64), "archetype" "public"."categories_archetype_enum" NOT NULL DEFAULT 'RETAIL', "nature" "public"."categories_nature_enum" NOT NULL DEFAULT 'PRODUCT', "actionVariant" "public"."categories_actionvariant_enum", "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_categories_active" ON "categories" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_archetype" ON "categories" ("archetype") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_parent" ON "categories" ("parentId") `);
        await queryRunner.query(`CREATE TABLE "service_provider_profile_categories" ("serviceProviderProfileId" uuid NOT NULL, "categoryId" character varying(64) NOT NULL, CONSTRAINT "PK_a0add12bf8968d9b5fd41918909" PRIMARY KEY ("serviceProviderProfileId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "idx_sp_profile_categories_category" ON "service_provider_profile_categories" ("categoryId") `);
        await queryRunner.query(`CREATE TYPE "public"."service_provider_profile_archetypes_archetype_enum" AS ENUM('RETAIL', 'RENTAL', 'BOOKING', 'LABOUR', 'REPAIR', 'SERVICE', 'EVENTS', 'ENTERTAINMENT', 'WHOLESALE', 'LENDING')`);
        await queryRunner.query(`CREATE TABLE "service_provider_profile_archetypes" ("serviceProviderProfileId" uuid NOT NULL, "archetype" "public"."service_provider_profile_archetypes_archetype_enum" NOT NULL, CONSTRAINT "PK_526a654dab991b8ebe6138449b6" PRIMARY KEY ("serviceProviderProfileId", "archetype"))`);
        await queryRunner.query(`CREATE INDEX "idx_sp_profile_archetypes_archetype" ON "service_provider_profile_archetypes" ("archetype") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_profiles_verificationstatus_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', 'INCOMPLETE')`);
        await queryRunner.query(`CREATE TABLE "seller_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying(255), "email" character varying(255), "phone" character varying(20), "dateOfBirth" date, "profilePicture" text, "logo" text, "coverImage" text, "socialLinks" text, "subRole" character varying(50), "companyName" character varying(255), "tpin" character varying(20), "incorporationCertUrl" text, "businessLicenseId" uuid, "verificationStatus" "public"."seller_profiles_verificationstatus_enum" NOT NULL DEFAULT 'PENDING', "verificationRejectionReason" text, "verifiedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "province" character varying(100), "city" character varying(100), "area" character varying(255), "latitude" numeric(10,7), "longitude" numeric(10,7), "radius" numeric(6,2), "pin" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_13845670b88adfde01026410969" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_seller_profiles_verification" ON "seller_profiles" ("verificationStatus") `);
        await queryRunner.query(`CREATE INDEX "idx_seller_profiles_user" ON "seller_profiles" ("userId") `);
        await queryRunner.query(`CREATE TABLE "seller_profile_categories" ("sellerProfileId" uuid NOT NULL, "categoryId" character varying(64) NOT NULL, CONSTRAINT "PK_140588b979d11aede6ab675c8eb" PRIMARY KEY ("sellerProfileId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "idx_seller_profile_categories_category" ON "seller_profile_categories" ("categoryId") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_profile_archetypes_archetype_enum" AS ENUM('RETAIL', 'RENTAL', 'BOOKING', 'LABOUR', 'REPAIR', 'SERVICE', 'EVENTS', 'ENTERTAINMENT', 'WHOLESALE', 'LENDING')`);
        await queryRunner.query(`CREATE TABLE "seller_profile_archetypes" ("sellerProfileId" uuid NOT NULL, "archetype" "public"."seller_profile_archetypes_archetype_enum" NOT NULL, CONSTRAINT "PK_d34ac5e5dddd96df919acb1c397" PRIMARY KEY ("sellerProfileId", "archetype"))`);
        await queryRunner.query(`CREATE INDEX "idx_seller_profile_archetypes_archetype" ON "seller_profile_archetypes" ("archetype") `);
        await queryRunner.query(`CREATE TYPE "public"."buyer_profiles_verificationstatus_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', 'INCOMPLETE')`);
        await queryRunner.query(`CREATE TABLE "buyer_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying(255), "email" character varying(255), "phone" character varying(20), "dateOfBirth" date, "profilePicture" text, "socialLinks" text, "subRole" character varying(50), "companyName" character varying(255), "tpin" character varying(20), "incorporationCertUrl" text, "businessLicenseId" uuid, "province" character varying(100), "city" character varying(100), "area" character varying(255), "latitude" numeric(10,7), "longitude" numeric(10,7), "radius" numeric(6,2), "categories" text NOT NULL DEFAULT '', "verificationStatus" "public"."buyer_profiles_verificationstatus_enum" NOT NULL DEFAULT 'PENDING', "verificationRejectionReason" text, "verifiedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "pin" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6e8158bfa9ea36f4a16df9c1f41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_buyer_profiles_verification" ON "buyer_profiles" ("verificationStatus") `);
        await queryRunner.query(`CREATE INDEX "idx_buyer_profiles_user" ON "buyer_profiles" ("userId") `);
        await queryRunner.query(`CREATE TABLE "shops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "logo" character varying(255), "coverImage" character varying(255), "location" character varying(255) NOT NULL, "latitude" numeric(10,6), "longitude" numeric(10,6), "socialLinks" json, "contactInfo" json, "isActive" boolean NOT NULL DEFAULT true, "rating" integer NOT NULL DEFAULT '0', "reviewCount" integer NOT NULL DEFAULT '0', "followerCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_94194bc87b70e0b20bf4d1709cf" UNIQUE ("sellerId"), CONSTRAINT "REL_94194bc87b70e0b20bf4d1709c" UNIQUE ("sellerId"), CONSTRAINT "PK_3c6aaa6607d287de99815e60b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_shops_name" ON "shops" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_shops_seller_id" ON "shops" ("sellerId") `);
        await queryRunner.query(`CREATE TYPE "public"."schedules_type_enum" AS ENUM('DELIVERY', 'MEETING', 'SERVICE', 'REMINDER', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."schedules_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "date" date NOT NULL, "startTime" TIME, "endTime" TIME, "type" "public"."schedules_type_enum" NOT NULL DEFAULT 'OTHER', "location" character varying(255), "status" "public"."schedules_status_enum" NOT NULL DEFAULT 'PENDING', "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_schedules_created_at" ON "schedules" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_schedules_type" ON "schedules" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_schedules_date" ON "schedules" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_schedules_user_id" ON "schedules" ("userId") `);
        await queryRunner.query(`CREATE TABLE "shop_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "providerUserId" uuid NOT NULL, "reviewerUserId" uuid NOT NULL, "orderId" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a23a106ac13b95287196f31407f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_shop_reviews_reviewer_order_unique" ON "shop_reviews" ("reviewerUserId", "orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_reviews_order" ON "shop_reviews" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_reviews_reviewer" ON "shop_reviews" ("reviewerUserId") `);
        await queryRunner.query(`CREATE INDEX "idx_shop_reviews_provider" ON "shop_reviews" ("providerUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."user_reports_category_enum" AS ENUM('SCAM_FRAUD', 'ABUSIVE_BEHAVIOR', 'NO_SHOW', 'FAKE_LISTING', 'PAYMENT_DISPUTE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."user_reports_contexttype_enum" AS ENUM('INQUIRY', 'QUOTE', 'ORDER')`);
        await queryRunner.query(`CREATE TYPE "public"."user_reports_status_enum" AS ENUM('OPEN', 'RESOLVED', 'DISMISSED')`);
        await queryRunner.query(`CREATE TABLE "user_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporterId" uuid NOT NULL, "reportedUserId" uuid NOT NULL, "category" "public"."user_reports_category_enum" NOT NULL, "description" text NOT NULL, "contextType" "public"."user_reports_contexttype_enum", "contextId" uuid, "status" "public"."user_reports_status_enum" NOT NULL DEFAULT 'OPEN', "resolutionNote" text, "resolvedByAdminId" uuid, "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d727f04c93f97a3d445a647d234" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_reports_created_at" ON "user_reports" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_user_reports_status" ON "user_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_user_reports_reported" ON "user_reports" ("reportedUserId") `);
        await queryRunner.query(`CREATE INDEX "idx_user_reports_reporter" ON "user_reports" ("reporterId") `);
        await queryRunner.query(`CREATE TABLE "referral_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "promoterUserId" uuid NOT NULL, "code" character varying(20) NOT NULL, "promoterName" character varying(255) NOT NULL, "promoterEmail" character varying(255) NOT NULL, "promoterPhone" character varying(20), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7fe9ab080167a0b65b5641511b3" UNIQUE ("code"), CONSTRAINT "PK_ba9165a54bafa386574ba5a8a6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_referral_links_promoter" ON "referral_links" ("promoterUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_referral_links_code" ON "referral_links" ("code") `);
        await queryRunner.query(`CREATE TABLE "promoter_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inviteKey" character varying(64) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1a51729078fc899cc5e76791707" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."promoter_profiles_verificationstatus_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "promoter_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bio" text, "socialLinks" json, "selfiePath" text, "idDocumentPath" text, "verificationStatus" "public"."promoter_profiles_verificationstatus_enum" NOT NULL DEFAULT 'PENDING', "rejectionReason" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d280da13463fd873ba384ac2f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_promoter_profiles_verification" ON "promoter_profiles" ("verificationStatus") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_promoter_profiles_user" ON "promoter_profiles" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."milestones_targetstage_enum" AS ENUM('inquiry', 'trade_complete')`);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "targetStage" "public"."milestones_targetstage_enum" NOT NULL, "requiredCount" integer NOT NULL, "equitySharesReward" numeric(12,2) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_milestones_active" ON "milestones" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_milestones_target_stage" ON "milestones" ("targetStage") `);
        await queryRunner.query(`CREATE TABLE "equity_awards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "promoterUserId" uuid NOT NULL, "milestoneId" uuid NOT NULL, "sharesAwarded" numeric(12,2) NOT NULL, "countAtAward" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_equity_awards_promoter_milestone" UNIQUE ("promoterUserId", "milestoneId"), CONSTRAINT "PK_2fc90680a729b9ff095bb9c5a52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_equity_awards_promoter" ON "equity_awards" ("promoterUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."conversions_funnelstage_enum" AS ENUM('registration', 'inquiry', 'trade_complete')`);
        await queryRunner.query(`CREATE TABLE "conversions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referralLinkId" uuid NOT NULL, "promoterUserId" uuid NOT NULL, "referredUserId" uuid NOT NULL, "funnelStage" "public"."conversions_funnelstage_enum" NOT NULL DEFAULT 'registration', "inquiryAdvancedAt" TIMESTAMP, "tradeCompleteAdvancedAt" TIMESTAMP, "firstInquiryId" uuid, "firstTradeSource" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4af8c6388f42a1849ee9b22fa16" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_conversions_promoter_stage" ON "conversions" ("promoterUserId", "funnelStage") `);
        await queryRunner.query(`CREATE INDEX "idx_conversions_referral_link" ON "conversions" ("referralLinkId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_conversions_referred_user" ON "conversions" ("referredUserId") `);
        await queryRunner.query(`CREATE TABLE "inquiry_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inquiryId" uuid NOT NULL, "imageUrl" character varying(500) NOT NULL, "imagePath" character varying(500) NOT NULL, "fileType" character varying(50), "fileSize" integer, "orderIndex" integer NOT NULL DEFAULT '0', "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2291ba3c93796f2741d87dcf96c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inquiries_processtype_enum" AS ENUM('EXPRESS', 'STANDARD')`);
        await queryRunner.query(`CREATE TYPE "public"."inquiries_status_enum" AS ENUM('OPEN', 'QUOTED', 'CLOSED')`);
        await queryRunner.query(`CREATE TYPE "public"."inquiries_currentstage_enum" AS ENUM('quotation', 'purchase_order', 'order_confirmation', 'delivery_order', 'completed')`);
        await queryRunner.query(`CREATE TABLE "inquiries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "displayId" character varying(20), "title" character varying(255) NOT NULL, "description" text NOT NULL, "buyerId" uuid NOT NULL, "location" character varying(255) NOT NULL, "province" character varying(100), "city" character varying(100), "latitude" numeric(10,6), "longitude" numeric(10,6), "radius" integer, "items" json, "preferences" json, "attributes" json, "processType" "public"."inquiries_processtype_enum" NOT NULL DEFAULT 'STANDARD', "status" "public"."inquiries_status_enum" NOT NULL DEFAULT 'OPEN', "currentStage" "public"."inquiries_currentstage_enum" NOT NULL DEFAULT 'quotation', "viewCount" integer NOT NULL DEFAULT '0', "maxQuotes" integer NOT NULL DEFAULT '3', "responseDeadlineAt" TIMESTAMP, "reserveReleasedAt" TIMESTAMP, "archivedBy" text NOT NULL DEFAULT '', "deletedBy" text NOT NULL DEFAULT '', "isLabour" boolean NOT NULL DEFAULT false, "labourGroup" character varying(50), "labourSubType" character varying(50), "targetedProviderId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a973122cd448b8a9f489278922f" UNIQUE ("displayId"), CONSTRAINT "PK_ceacaa439988b25eb9459e694d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_inquiries_display_id" ON "inquiries" ("displayId") `);
        await queryRunner.query(`CREATE INDEX "idx_inquiries_buyer_status" ON "inquiries" ("buyerId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_inquiries_created_at" ON "inquiries" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_inquiries_location" ON "inquiries" ("location") `);
        await queryRunner.query(`CREATE INDEX "idx_inquiries_status" ON "inquiries" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_inquiries_buyer_id" ON "inquiries" ("buyerId") `);
        await queryRunner.query(`CREATE TYPE "public"."quotes_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'ARCHIVED', 'PAID', 'PENDING_COLLECTION', 'AWAITING_PICKUP', 'COMPLETED', 'HANDED_OVER', 'SUPERSEDED')`);
        await queryRunner.query(`CREATE TYPE "public"."quotes_processtype_enum" AS ENUM('EXPRESS', 'STANDARD')`);
        await queryRunner.query(`CREATE TYPE "public"."quotes_quotetype_enum" AS ENUM('ORIGINAL', 'REVISION')`);
        await queryRunner.query(`CREATE TYPE "public"."quotes_slottier_enum" AS ENUM('PRIMARY', 'RESERVE')`);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inquiryId" uuid NOT NULL, "inquiryTitle" character varying(255) NOT NULL, "providerId" uuid NOT NULL, "providerName" character varying(255) NOT NULL, "price" numeric(12,2) NOT NULL, "condition" character varying(50) NOT NULL, "message" text NOT NULL, "status" "public"."quotes_status_enum" NOT NULL DEFAULT 'PENDING', "expiryDuration" character varying(50), "isRead" boolean NOT NULL DEFAULT false, "isArchived" boolean NOT NULL DEFAULT false, "itemPrices" json, "buyerContact" json, "collectionCode" character varying(50), "requirements" json, "venueSpaceId" uuid, "venueSpaceName" character varying(255), "damageDeposit" numeric(12,2), "cleaningFee" numeric(12,2), "dynamicFields" json, "processType" "public"."quotes_processtype_enum" NOT NULL DEFAULT 'STANDARD', "delivery" json, "pickupLocation" character varying(255), "quoteType" "public"."quotes_quotetype_enum" NOT NULL DEFAULT 'ORIGINAL', "parentQuoteId" uuid, "slotTier" "public"."quotes_slottier_enum" NOT NULL DEFAULT 'PRIMARY', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_quotes_inquiry_provider" ON "quotes" ("inquiryId", "providerId") `);
        await queryRunner.query(`CREATE INDEX "idx_quotes_created_at" ON "quotes" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_quotes_status" ON "quotes" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_quotes_provider_id" ON "quotes" ("providerId") `);
        await queryRunner.query(`CREATE INDEX "idx_quotes_inquiry_id" ON "quotes" ("inquiryId") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sellerId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "category" character varying(100) NOT NULL, "subCategory" character varying(100), "price" numeric(12,2) NOT NULL, "originalPrice" numeric(12,2), "stock" integer NOT NULL DEFAULT '0', "images" text NOT NULL DEFAULT '', "brand" character varying(100), "condition" character varying(50), "attributes" json, "isActive" boolean NOT NULL DEFAULT true, "viewCount" integer NOT NULL DEFAULT '0', "rating" numeric(3,2) NOT NULL DEFAULT '0', "reviewCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_products_seller_category" ON "products" ("sellerId", "category") `);
        await queryRunner.query(`CREATE INDEX "idx_products_created_at" ON "products" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_products_name" ON "products" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_products_category" ON "products" ("category") `);
        await queryRunner.query(`CREATE INDEX "idx_products_seller_id" ON "products" ("sellerId") `);
        await queryRunner.query(`CREATE TABLE "portfolio_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying(255) NOT NULL, "youtubeUrl" text NOT NULL, "eventName" character varying(255), "eventDate" date, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c636df11b3cc98f390c8efc656a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_portfolio_user_id" ON "portfolio_items" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_type_enum" AS ENUM('DEPOSIT', 'PAYMENT', 'WITHDRAWAL', 'REFUND', 'TRANSFER')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transactionId" character varying(50) NOT NULL, "userId" uuid NOT NULL, "type" "public"."payments_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "fee" numeric(12,2) NOT NULL DEFAULT '0', "netAmount" numeric(12,2) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "externalReference" character varying(255), "paymentMethod" character varying(50), "description" text, "metadata" json, "processedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c39d78e8744809ece8ca95730e2" UNIQUE ("transactionId"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_payments_reference" ON "payments" ("externalReference") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_created_at" ON "payments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_type" ON "payments" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_user_id" ON "payments" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quoteId" uuid NOT NULL, "buyerId" uuid NOT NULL, "sellerId" uuid NOT NULL, "orderNumber" character varying(50) NOT NULL, "totalAmount" numeric(12,2) NOT NULL, "deliveryFee" numeric(12,2), "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "shippingAddress" character varying(255), "notes" text, "items" json, "deliveryDate" TIMESTAMP, "trackingNumber" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_59b0c3b34ea0fa5562342f24143" UNIQUE ("orderNumber"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_orders_buyer_seller" ON "orders" ("buyerId", "sellerId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_created_at" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_seller_id" ON "orders" ("sellerId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_buyer_id" ON "orders" ("buyerId") `);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "endpoint" character varying NOT NULL, "p256dh" character varying NOT NULL, "auth" character varying NOT NULL, "userAgent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0008bdfd174e533a3f98bf9af16" UNIQUE ("endpoint"), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_push_subscriptions_user" ON "push_subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('NEW_LEAD', 'QUOTE_RECEIVED', 'RESERVE_RELEASED', 'MILESTONE_UNLOCKED')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('PENDING', 'ACKNOWLEDGED', 'DECLINED')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "inquiryId" uuid, "quoteId" uuid, "title" character varying(255) NOT NULL, "data" json, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'PENDING', "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_inquiry" ON "notifications" ("userId", "inquiryId") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_created" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "inquiry_categories" ("inquiryId" uuid NOT NULL, "categoryId" character varying(64) NOT NULL, CONSTRAINT "PK_020fb283a38d2f5105f103b27e9" PRIMARY KEY ("inquiryId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "idx_inquiry_categories_category" ON "inquiry_categories" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "shop_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "paidUntil" TIMESTAMP, "lastAmount" numeric(10,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8ad5edcf86a22b82e678747220" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_shop_subscriptions_user" ON "shop_subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "billing_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionsEnabled" boolean NOT NULL DEFAULT false, "quoteTiers" json, "targetedInquiryFee" numeric(10,2) NOT NULL DEFAULT '10', "monthlyFee" numeric(10,2) NOT NULL DEFAULT '100', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_50de306c9059fe5297a3483516a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "providerId" uuid, "staffId" uuid, "staffName" character varying(100), "action" character varying(50) NOT NULL, "entityType" character varying(100) NOT NULL, "entityId" uuid, "targetTitle" character varying(255), "buyerName" character varying(100), "amount" numeric(12,2), "details" text, "changes" text, "status" character varying(50), "reason" text, "ipAddress" character varying(45), "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("userId") `);
        await queryRunner.query(`ALTER TABLE "identity_audits" ADD CONSTRAINT "FK_e60657b2e187dbb58ff8723027e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_emails" ADD CONSTRAINT "FK_569342223a28f006d9bf897c7c9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_profiles" ADD CONSTRAINT "FK_81d38487c29d69bf340eead614c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_profile_categories" ADD CONSTRAINT "FK_a1c16ab5aad6d477ce065bf301e" FOREIGN KEY ("serviceProviderProfileId") REFERENCES "service_provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_profile_categories" ADD CONSTRAINT "FK_865af2333668e52879d95b2f77c" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_provider_profile_archetypes" ADD CONSTRAINT "FK_12c1f2fa32991a62c3d388caa48" FOREIGN KEY ("serviceProviderProfileId") REFERENCES "service_provider_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_profiles" ADD CONSTRAINT "FK_49de7dde25d76b120677be9aedd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_profile_categories" ADD CONSTRAINT "FK_2030b121d12b432aa8e6aa34edc" FOREIGN KEY ("sellerProfileId") REFERENCES "seller_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_profile_categories" ADD CONSTRAINT "FK_92eda646e9aab879835181b4d6c" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_profile_archetypes" ADD CONSTRAINT "FK_029c7239232830b044f6c99f48c" FOREIGN KEY ("sellerProfileId") REFERENCES "seller_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer_profiles" ADD CONSTRAINT "FK_38b83d9a65dc1c0e43333cb3098" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shops" ADD CONSTRAINT "FK_94194bc87b70e0b20bf4d1709cf" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_19c54f24597b318be3892114c75" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_links" ADD CONSTRAINT "FK_5e61798a2f485ea77564e186384" FOREIGN KEY ("promoterUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promoter_profiles" ADD CONSTRAINT "FK_5df7ef682e3f8d733bdd04a3f0b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equity_awards" ADD CONSTRAINT "FK_0fb9db9fffd14cccc1fd31256e3" FOREIGN KEY ("promoterUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equity_awards" ADD CONSTRAINT "FK_a04ad502886cedcb7174e5373b6" FOREIGN KEY ("milestoneId") REFERENCES "milestones"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversions" ADD CONSTRAINT "FK_ce3cce79aaca49f0a12ef982f7e" FOREIGN KEY ("referralLinkId") REFERENCES "referral_links"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiry_images" ADD CONSTRAINT "FK_a56e3d4f414c421b54e4d4bb5cb" FOREIGN KEY ("inquiryId") REFERENCES "inquiries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiries" ADD CONSTRAINT "FK_6dbe27695adbaec51c080f17c62" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_3756cd4fd06b4be90b29be01e11" FOREIGN KEY ("inquiryId") REFERENCES "inquiries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_9bcf61ad282d63066168f99dc8f" FOREIGN KEY ("providerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_e40a1dd2909378f0da1f34f7bd6" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_items" ADD CONSTRAINT "FK_7ec721ebc4a2c3f8b31f45937fc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_95a206b8b8cafbd842d39aba6cf" FOREIGN KEY ("quoteId") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d" FOREIGN KEY ("buyerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_1c382880db667beb75d26c57873" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_4cc061875e9eecc311a94b3e431" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiry_categories" ADD CONSTRAINT "FK_3f4e1e46a5a8e52cac8d9530294" FOREIGN KEY ("inquiryId") REFERENCES "inquiries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inquiry_categories" ADD CONSTRAINT "FK_335d1e0cb1d16a9c77b23c25c9c" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop_subscriptions" ADD CONSTRAINT "FK_7c039498326e0064b68e96754d6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "shop_subscriptions" DROP CONSTRAINT "FK_7c039498326e0064b68e96754d6"`);
        await queryRunner.query(`ALTER TABLE "inquiry_categories" DROP CONSTRAINT "FK_335d1e0cb1d16a9c77b23c25c9c"`);
        await queryRunner.query(`ALTER TABLE "inquiry_categories" DROP CONSTRAINT "FK_3f4e1e46a5a8e52cac8d9530294"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_4cc061875e9eecc311a94b3e431"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_1c382880db667beb75d26c57873"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_9877ffd9a491c3e82f5b32d4f4d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_95a206b8b8cafbd842d39aba6cf"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "portfolio_items" DROP CONSTRAINT "FK_7ec721ebc4a2c3f8b31f45937fc"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_e40a1dd2909378f0da1f34f7bd6"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_9bcf61ad282d63066168f99dc8f"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_3756cd4fd06b4be90b29be01e11"`);
        await queryRunner.query(`ALTER TABLE "inquiries" DROP CONSTRAINT "FK_6dbe27695adbaec51c080f17c62"`);
        await queryRunner.query(`ALTER TABLE "inquiry_images" DROP CONSTRAINT "FK_a56e3d4f414c421b54e4d4bb5cb"`);
        await queryRunner.query(`ALTER TABLE "conversions" DROP CONSTRAINT "FK_ce3cce79aaca49f0a12ef982f7e"`);
        await queryRunner.query(`ALTER TABLE "equity_awards" DROP CONSTRAINT "FK_a04ad502886cedcb7174e5373b6"`);
        await queryRunner.query(`ALTER TABLE "equity_awards" DROP CONSTRAINT "FK_0fb9db9fffd14cccc1fd31256e3"`);
        await queryRunner.query(`ALTER TABLE "promoter_profiles" DROP CONSTRAINT "FK_5df7ef682e3f8d733bdd04a3f0b"`);
        await queryRunner.query(`ALTER TABLE "referral_links" DROP CONSTRAINT "FK_5e61798a2f485ea77564e186384"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_19c54f24597b318be3892114c75"`);
        await queryRunner.query(`ALTER TABLE "shops" DROP CONSTRAINT "FK_94194bc87b70e0b20bf4d1709cf"`);
        await queryRunner.query(`ALTER TABLE "buyer_profiles" DROP CONSTRAINT "FK_38b83d9a65dc1c0e43333cb3098"`);
        await queryRunner.query(`ALTER TABLE "seller_profile_archetypes" DROP CONSTRAINT "FK_029c7239232830b044f6c99f48c"`);
        await queryRunner.query(`ALTER TABLE "seller_profile_categories" DROP CONSTRAINT "FK_92eda646e9aab879835181b4d6c"`);
        await queryRunner.query(`ALTER TABLE "seller_profile_categories" DROP CONSTRAINT "FK_2030b121d12b432aa8e6aa34edc"`);
        await queryRunner.query(`ALTER TABLE "seller_profiles" DROP CONSTRAINT "FK_49de7dde25d76b120677be9aedd"`);
        await queryRunner.query(`ALTER TABLE "service_provider_profile_archetypes" DROP CONSTRAINT "FK_12c1f2fa32991a62c3d388caa48"`);
        await queryRunner.query(`ALTER TABLE "service_provider_profile_categories" DROP CONSTRAINT "FK_865af2333668e52879d95b2f77c"`);
        await queryRunner.query(`ALTER TABLE "service_provider_profile_categories" DROP CONSTRAINT "FK_a1c16ab5aad6d477ce065bf301e"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "service_provider_profiles" DROP CONSTRAINT "FK_81d38487c29d69bf340eead614c"`);
        await queryRunner.query(`ALTER TABLE "user_emails" DROP CONSTRAINT "FK_569342223a28f006d9bf897c7c9"`);
        await queryRunner.query(`ALTER TABLE "identity_audits" DROP CONSTRAINT "FK_e60657b2e187dbb58ff8723027e"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_created_at"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "billing_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_subscriptions_user"`);
        await queryRunner.query(`DROP TABLE "shop_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiry_categories_category"`);
        await queryRunner.query(`DROP TABLE "inquiry_categories"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_inquiry"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_push_subscriptions_user"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_buyer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_seller_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_buyer_seller"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_reference"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portfolio_user_id"`);
        await queryRunner.query(`DROP TABLE "portfolio_items"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_seller_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_seller_category"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quotes_inquiry_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quotes_provider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quotes_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quotes_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_quotes_inquiry_provider"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_slottier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_quotetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_processtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiries_buyer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiries_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiries_location"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiries_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiries_buyer_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_inquiries_display_id"`);
        await queryRunner.query(`DROP TABLE "inquiries"`);
        await queryRunner.query(`DROP TYPE "public"."inquiries_currentstage_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inquiries_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inquiries_processtype_enum"`);
        await queryRunner.query(`DROP TABLE "inquiry_images"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_referred_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_referral_link"`);
        await queryRunner.query(`DROP INDEX "public"."idx_conversions_promoter_stage"`);
        await queryRunner.query(`DROP TABLE "conversions"`);
        await queryRunner.query(`DROP TYPE "public"."conversions_funnelstage_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_equity_awards_promoter"`);
        await queryRunner.query(`DROP TABLE "equity_awards"`);
        await queryRunner.query(`DROP INDEX "public"."idx_milestones_target_stage"`);
        await queryRunner.query(`DROP INDEX "public"."idx_milestones_active"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_targetstage_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_promoter_profiles_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_promoter_profiles_verification"`);
        await queryRunner.query(`DROP TABLE "promoter_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."promoter_profiles_verificationstatus_enum"`);
        await queryRunner.query(`DROP TABLE "promoter_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_links_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_referral_links_promoter"`);
        await queryRunner.query(`DROP TABLE "referral_links"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_reports_reporter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_reports_reported"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_reports_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_reports_created_at"`);
        await queryRunner.query(`DROP TABLE "user_reports"`);
        await queryRunner.query(`DROP TYPE "public"."user_reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_reports_contexttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_reports_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_reviews_provider"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_reviews_reviewer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_reviews_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shop_reviews_reviewer_order_unique"`);
        await queryRunner.query(`DROP TABLE "shop_reviews"`);
        await queryRunner.query(`DROP INDEX "public"."idx_schedules_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_schedules_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_schedules_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_schedules_created_at"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shops_seller_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_shops_name"`);
        await queryRunner.query(`DROP TABLE "shops"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buyer_profiles_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buyer_profiles_verification"`);
        await queryRunner.query(`DROP TABLE "buyer_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."buyer_profiles_verificationstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seller_profile_archetypes_archetype"`);
        await queryRunner.query(`DROP TABLE "seller_profile_archetypes"`);
        await queryRunner.query(`DROP TYPE "public"."seller_profile_archetypes_archetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seller_profile_categories_category"`);
        await queryRunner.query(`DROP TABLE "seller_profile_categories"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seller_profiles_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seller_profiles_verification"`);
        await queryRunner.query(`DROP TABLE "seller_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."seller_profiles_verificationstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sp_profile_archetypes_archetype"`);
        await queryRunner.query(`DROP TABLE "service_provider_profile_archetypes"`);
        await queryRunner.query(`DROP TYPE "public"."service_provider_profile_archetypes_archetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sp_profile_categories_category"`);
        await queryRunner.query(`DROP TABLE "service_provider_profile_categories"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_archetype"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_active"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_actionvariant_enum"`);
        await queryRunner.query(`DROP TYPE "public"."categories_nature_enum"`);
        await queryRunner.query(`DROP TYPE "public"."categories_archetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_service_provider_profiles_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_service_provider_profiles_verification"`);
        await queryRunner.query(`DROP TABLE "service_provider_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."service_provider_profiles_verificationstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_emails_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_emails_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_emails_is_primary"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_emails_verification_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_emails_created_at"`);
        await queryRunner.query(`DROP TABLE "user_emails"`);
        await queryRunner.query(`DROP TYPE "public"."user_emails_verificationstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_nrc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_display_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_updated_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_password_reset_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_parent_provider"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_departmentautonomy_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_activeprofiletype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_identity_audits_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_identity_audits_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_identity_audits_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_identity_audits_user_event"`);
        await queryRunner.query(`DROP INDEX "public"."idx_identity_audits_user_date"`);
        await queryRunner.query(`DROP TABLE "identity_audits"`);
        await queryRunner.query(`DROP TYPE "public"."identity_audits_verificationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."identity_audits_eventtype_enum"`);
    }

}
